#ifndef ADBLOCK_FFI_H
#define ADBLOCK_FFI_H

// Generated by cbindgen from src/lib.rs. Do not edit by hand.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle. Swift holds `OpaquePointer`; the layout is never exposed.
 */
typedef struct AdblockEngine AdblockEngine;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Build an engine from filter-list text (one or more lists concatenated).
 *
 * Returns null if `rules` is null, not UTF-8, or the parse panics. The engine
 * is built without debug info: rule provenance costs memory and only the
 * converter below needs it.
 *
 * # Safety
 * `rules` must be a valid NUL-terminated C string.
 */
struct AdblockEngine *adblock_engine_create(const char *rules);

/**
 * Build an engine, optionally parsing the rules as a *trusted* list.
 *
 * Scriptlet rules whose name begins with `trusted-` are dropped at parse time
 * unless the list carries the permission for them, and `ParseOptions::default()`
 * carries none. That is not a detail: the rules that strip ads out of a video
 * site's own player response are `trusted-replace-fetch-response` and
 * `trusted-replace-xhr-response`, so a list parsed without the permission
 * silently loses exactly the rules that do the work — no error, no log, just
 * ads.
 *
 * The permission exists because these scriptlets can rewrite any response body
 * on any site, which is a capability you extend to a list you chose, not to
 * every list on the internet. So it is a parameter rather than a default: the
 * caller decides which lists it trusts.
 *
 * # Safety
 * `rules` must be a valid NUL-terminated C string.
 */
struct AdblockEngine *adblock_engine_create_with_trust(const char *rules, bool trusted);

/**
 * Rebuild an engine from the bytes produced by [`adblock_engine_serialize`].
 *
 * Parsing EasyList takes seconds; reloading a serialized engine takes
 * milliseconds, which is the difference between blocking working on the first
 * page load after launch and working a few seconds later.
 *
 * # Safety
 * `data` must point to at least `len` readable bytes.
 */
struct AdblockEngine *adblock_engine_create_from_serialized(const uint8_t *data, uintptr_t len);

/**
 * Release an engine. Null is a no-op; passing the same pointer twice is not.
 *
 * # Safety
 * `engine` must have come from one of the create functions and not been freed.
 */
void adblock_engine_free(struct AdblockEngine *engine);

/**
 * Should this request be blocked?
 *
 * `request_type` is the adblock resource type — `script`, `image`,
 * `xmlhttprequest`, `sub_frame`/`subdocument`, `stylesheet`, `media`,
 * `websocket`, `fetch`, `other`. First/third-party is derived from `url`
 * against `source_url`, so the caller doesn't have to work it out.
 *
 * Returns `false` for any malformed input: failing open matches what a browser
 * should do when it can't classify a request.
 *
 * # Safety
 * All pointers must be valid NUL-terminated C strings; `engine` must be live.
 */
bool adblock_engine_matches(const struct AdblockEngine *engine,
                            const char *url,
                            const char *source_url,
                            const char *request_type);

/**
 * Cosmetic filters for a page, as JSON: `hide_selectors`, `procedural_actions`,
 * `exceptions`, `injected_script`, `generichide`.
 *
 * `injected_script` is executable JavaScript assembled from the bundled
 * scriptlet resources. It must only ever come from resources compiled into the
 * app — App Store guideline 2.5.2 does not permit downloading and running code.
 *
 * Returns null on failure. Free with [`adblock_string_free`].
 *
 * # Safety
 * `engine` must be live and `url` a valid NUL-terminated C string.
 */
char *adblock_engine_cosmetic_resources(const struct AdblockEngine *engine, const char *url);

/**
 * Load the scriptlet resources that `+js(...)` filter rules inject.
 *
 * `resources_json` is the standard resources array: `name`, `aliases`, `kind`,
 * and base64 `content`. Without this, `injected_script` in the cosmetic
 * resources is always empty, because a `+js(...)` rule names a scriptlet the
 * engine has no body for.
 *
 * These resources are executable JavaScript and must be compiled into the app.
 * Fetching them over the network would be downloading code, which App Store
 * guideline 2.5.2 does not permit — unlike the filter lists themselves, which
 * are data and may be updated.
 *
 * Returns false if the payload is missing, not UTF-8, or not a resources array.
 *
 * # Safety
 * `engine` must be live and `resources_json` a valid NUL-terminated C string.
 */
bool adblock_engine_use_resources(struct AdblockEngine *engine, const char *resources_json);

/**
 * Generic cosmetic selectors matching the classes and ids actually present on a
 * page.
 *
 * The great majority of EasyList's cosmetic rules are generic — `##.ad-banner`
 * with no domain — and [`adblock_engine_cosmetic_resources`] deliberately does
 * not return them: there are hundreds of thousands, and only the handful whose
 * class or id appears in the document matter. So the page reports what it
 * contains and gets back the subset that applies.
 *
 * `classes_json`, `ids_json` and `exceptions_json` are JSON arrays of strings;
 * `exceptions` is the `exceptions` field from the call above. Returns a JSON
 * array of selectors, or null on failure. Free with [`adblock_string_free`].
 *
 * # Safety
 * All pointers must be valid NUL-terminated C strings; `engine` must be live.
 */
char *adblock_engine_hidden_class_id_selectors(const struct AdblockEngine *engine,
                                               const char *classes_json,
                                               const char *ids_json,
                                               const char *exceptions_json);

/**
 * Serialize an engine so the next launch can skip parsing. Writes the length
 * to `out_len` and returns the buffer, or null on failure.
 *
 * Free with [`adblock_bytes_free`], passing back the same length.
 *
 * # Safety
 * `engine` must be live; `out_len` must be a valid writable pointer.
 */
uint8_t *adblock_engine_serialize(const struct AdblockEngine *engine, uintptr_t *out_len);

/**
 * Release a buffer from [`adblock_engine_serialize`].
 *
 * # Safety
 * `data`/`len` must be exactly what `adblock_engine_serialize` returned.
 */
void adblock_bytes_free(uint8_t *data, uintptr_t len);

/**
 * Convert filter-list text into Apple content-blocker JSON, ready for
 * `WKContentRuleListStore.compileContentRuleList`.
 *
 * This is the engine's most important job on iOS: `WKNavigationDelegate` never
 * sees subresource requests, so declarative rules compiled into WebKit are the
 * only way to block images, scripts and frames at all.
 *
 * Note the `FilterSet` is built in debug mode — the converter refuses to run
 * without it, because it needs the original rule text to emit triggers.
 *
 * Rules WebKit can't express are dropped rather than failing the batch. That
 * loss is not evenly distributed and it matters: most exception (`@@`) rules use
 * options the declarative syntax has no equivalent for, so they disappear while
 * the block rules they were written to override survive. The result is
 * over-blocking. `network_only` exists because of the same problem in cosmetic
 * rules — see below.
 *
 * With `network_only` set, cosmetic rules are left out entirely. Converting them
 * produces `css-display-none` entries that apply to every site with no way to
 * honour `#@#` unhide rules or `$generichide` exceptions, which hides legitimate
 * page content. The runtime engine applies the same rules correctly, scoped per
 * URL and with exceptions intact, so the declarative copy is pure downside.
 *
 * Returns null only if nothing could be produced. Free with
 * [`adblock_string_free`].
 *
 * # Safety
 * `filter_set` must be a valid NUL-terminated C string.
 */
char *adblock_content_blocker_rules(const char *filter_set, bool network_only);

/**
 * Release a string returned by this library.
 *
 * # Safety
 * `value` must have come from this library and not been freed.
 */
void adblock_string_free(char *value);

/**
 * Version of the underlying `adblock` crate, for logging and cache
 * invalidation — a serialized engine from a different version won't load.
 * The returned string is static and must not be freed.
 */
const char *adblock_engine_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ADBLOCK_FFI_H */
